<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <AssemblyName>System.Test</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="NUnit.Runners" Version="3.12.0" />
    <PackageReference Include="Appveyor.TestLogger" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="SqlStreamStore.MsSql" Version="1.2.0" />
    <PackageReference Include="SqlStreamStore.Postgres" Version="1.2.0-beta.8" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Memstate.EventStore\Memstate.EventStore.csproj" />
    <ProjectReference Include="..\Memstate.JsonNet\Memstate.JsonNet.csproj" />
    <ProjectReference Include="..\Memstate.MsConfig\Memstate.MsConfig.csproj" />
    <ProjectReference Include="..\Memstate.Wire\Memstate.Wire.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="TestOutputLogger.cs" />
  </ItemGroup>
</Project>